# Generated by Django 2.2.5 on 2019-09-26 07:23

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='progression',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='avancement (%)'),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='progression',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='avancement (%)'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour')),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0, 25200), verbose_name='durée')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='commentaire')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project', verbose_name='projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'ressource',
                'verbose_name_plural': 'ressources',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalResource',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='mise à jour')),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0, 25200), verbose_name='durée')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='commentaire')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.Project', verbose_name='projet')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'historical ressource',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCapacity',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='mise à jour')),
                ('date', models.DateField()),
                ('duration', models.DurationField(default=datetime.timedelta(0, 25200), verbose_name='durée')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='commentaire')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='capacity', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'historical capacité',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour')),
                ('date', models.DateField()),
                ('duration', models.DurationField(default=datetime.timedelta(0, 25200), verbose_name='durée')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='commentaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacities', related_query_name='capacity', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'capacité',
                'verbose_name_plural': 'capacités',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='resources',
            field=models.ManyToManyField(related_name='projects', related_query_name='project', through='projects.Resource', to=settings.AUTH_USER_MODEL, verbose_name='ressources'),
        ),
    ]
